aumentos_tier_1 = [
    "Adaptive Strikes",
    "AFK",
    "Backup",
    "Band of Thieves I",
    "Big Friend I",
    "Blistering Strikes",
    "Branching Out",
    "Branching Out+",
    "Bulky Buddies I",
    "Button Mash",
    "Called Shot",
    "Caretaker's Ally",
    "Cease and Desist",
    "Climb The Ladder I",
    "Component Buffet",
    "Corrosion",
    "Crafted Crafting",
    "Delayed Start",
    "Diversified Portfolio",
    "Diversified Portfolio+",
    "Dummify",
    "Eye For An Eye",
    "Eye For An Eye+",
    "Find Your Center",
    "Firesale",
    "Glass Cannon I",
    "Good For Something I",
    "Healing Orbs I",
    "Health is Wealth I",
    "Iron Assets",
    "Item Collector I",
    "Item Grab Bag I",
    "Kingslayer",
    "Lategame Specialisst",
    "Latent Forge",
    "Lineup",
    "Lunch Money",
    "Manaflow I",
    "Mentorship I",
    "Missed Connections",
    "One For All I",
    "One, Two, Five!",
    "One, Twos, Three",
    "Over Encumbered",
    "Pandora's Bench",
    "Pandora's Items",
    "Patience Is a Virtue",
    "Placebo",
    "Placebo+",
    "Preparation I",
    "Pumping Up I",
    "Recombulator",
    "Restart Mission",
    "Rigged Shop",
    "Rigged Shop+",
    "Risky Moves",
    "Rolling for Days I",
    "Sivler Spoon",
    "Spoilss of War I",
    "Stand United I",
    "Support Mining",
    "Support Mining+",
    "Survivor",
    "Table Scraps",
    "Team Building",
    "Teaming Up I",
    "Titanic Titan",
    "Underdogs",
    "Wolf Unchained",
    "Young and Wild and Free",
]

aumentos_tier_2 = [
    "10,000 IQ",
    "10,000 IQ+",
    "All That Shimmers",
    "All That Shimmers+",
    "Alter Ego",
    "A Magic Roll",
    "Anima Squad Crest",
    "Ascension",
    "Bad Luck Protection",
    "Bastion Crest",
    "Big Friend II",
    "Big Grab Bag",
    "Blazing Soul I",
    "Board of Directors",
    "BoomBots Crest",
    "BRB",
    "Bronze For Life I",
    "Bruiser Crest",
    "Bulky Buddies II",
    "Calculated Loss",
    "Capacitor",
    "Caretaker's Favor",
    "Clear Mind",
    "Climb The Ladder II",
    "Clockwork Accelerator",
    "Cloning Facility",
    "Cluttered Mind",
    "Cognitive Implant",
    "Cooking Pot",
    "Cower, Weakling!",
    "Crown Guarded",
    "Crown's Will",
    "Cutpurse",
    "Cyberdeck",
    "Cybernetic Bulk II",
    "Cybernetic Implants II",
    "Cybernetic Uplink II",
    "Divine Ascension",
    "Divinicorp Crest",
    "Dummy With A Gun",
    "Duo Queue",
    "Dynamo Crest",
    "Epoch",
    "Epoch+",
    "Executioner Crest",
    "Exotech Crest",
    "Flatline",
    "Forward Thinking",
    "Freestyling",
    "Glass Cannon II",
    "Golden Fleece",
    "Golden Fleece+",
    "Golden Ox Crest",
    "Gold For Dummies",
    "Golemify",
    "Healing Obrs II",
    "Health is Wealth II",
    "Heroic Grab Bag",
    "Heroic Grab Bag+",
    "Heroic Grab Bag++",
    "High Voltage",
    "Hostile Takeover",
    "Hunter Killer Missile",
    "Hustler",
    "Inspiring Epitaph",
    "Investment Strategy I",
    "Item Collector II",
    "Keep Your Friends Close",
    "Last Stand",
    "Lethal Rerouting",
    "Little Buddies",
    "Long Distance Pals",
    "Mace's Will",
    "Malicious Monetization",
    "Manaflow II",
    "Marksman Crest",
    "Memory Bank",
    "Mentorship II",
    "Moonlight",
    "New High Score",
    "Noble Sacrifice",
    "NO SCOUT NO PIVOT",
    "Not Today",
    "One For All II",
    "Overheal",
    "Pair of Fours",
    "Pandora's Items II",
    "Patient Study",
    "Piercing Lotus I",
    "Pilfer",
    "Polished Chrome",
    "Portable Forge",
    "Power Leveling",
    "Preparation II",
    "Prizefighter",
    "Pumping Up II",
    "Pyromaniac",
    "Raining Gold",
    "Raining Gold+",
    "Rapidfire Crest",
    "Reactive Shell",
    "Reinforcing Skeleture",
    "ReinFOURcement",
    "Replication",
    "Salvage Bing",
    "Salvage Bin+",
    "Sated Spellweaver",
    "Scapegoat",
    "Scavenger",
    "Scoreboard Scrapper",
    "Shop Glitch",
    "Slammin",
    "Slammin+",
    "Slayer Crest",
    "Spear's Will",
    "Speed Kills",
    "Spirit Link",
    "Spoils of War II",
    "Starry Night",
    "Starry Night+",
    "Strategist Crest",
    "Street Demon Crest",
    "Support Cache",
    "Support Spire",
    "Syndicate Crest",
    "Tagging Spree",
    "Teaming Up II",
    "Techie Crest",
    "The Chug Bug",
    "The Chug Bug+",
    "Thorn-Plated Armor",
    "Tomb Raider I",
    "Tower Defense",
    "Trade Sector",
    "Trait Tracker",
    "Transistor",
    "Trial Run",
    "Trifecta I",
    "Two Much Value",
    "Vampiric Vitality",
    "Vanguard Crest",
    "Wandering Trainer I",
    "Warpath",
    "Worth the Wait I",
]

aumentos_tier_3 = [
    "An Exalted Adventure",
    "Anima Squad Circlet",
    "Axion Arc III",
    "Bastion Circlet",
    "Bastion Crown",
    "Belt Overflow",
    "Binary Airdrop",
    "Birthday Present",
    "Blazing Soul II",
    "Blinding Speed",
    "Blue Battery III",
    "BoomBots Circlet",
    "BoomBots Crown",
    "Bronze For Life II",
    "Bruiser Circlet",
    "Bruiser Crown",
    "Build a Bud!",
    "Bulky Buddies III",
    "Buried Treasures III",
    "Calculated Enhancement",
    "Call to Chaos",
    "Caretaker's Chosen",
    "Chemtech Overdrive",
    "Coronation",
    "Cruel Pact",
    "Cursed Crown",
    "Cybernetic Bulk III",
    "Cybernetic Implants III",
    "Cybernetic Uplink III",
    "Divinicorp Circlet",
    "Divinicorp Crown",
    "Dominance",
    "Double Trouble III",
    "Dual Purpose",
    "Dynamo Circlet",
    "Dynamo Crown",
    "Endless Horde+",
    "Endless Hordes",
    "Executioner Circlet",
    "Executioner Crown",
    "Exotech Circlet",
    "Exotech Crown",
    "Expected Unexpectedness",
    "Final Ascension",
    "Final Polish",
    "Final Reserves",
    "Flexible",
    "Flurry of Blows",
    "Gargantuan Resolve",
    "Going Long",
    "Golden Ox Circlet",
    "Golden Ox Crown",
    "Greater Moonlight",
    "Hard Commit",
    "Hedge Fund",
    "High End Shopping II",
    "Immovable Object",
    "I'm the Carry now",
    "Invested+",
    "Invested++",
    "Invetment Strategy II",
    "Level Up!",
    "Lifelong Learning",
    "Living Forge",
    "Lucky Gloves",
    "Lucky Gloves+",
    "Luden's Echo III",
    "Marksman Circlet",
    "Marksman Crown",
    "Max Cap",
    "One Buff, Two Buff",
    "Pandora's Items III",
    "Phreaky Friday",
    "Phreaky Firday+´",
    "Piercing Lotus II",
    "Pirates",
    "Prismatic Pipeline",
    "Prismatic Ticket",
    "Pumping Up III",
    "Quality Over Quantity",
    "Radiant Refactor",
    "Radiant Relics",
    "Rapidfire Circlet",
    "Rapidfire Crown",
    "Roll The Dice",
    "Scoped Weapons II",
    "Share The Spotlight",
    "Shimmerscale Essence",
    "Shopping Spree",
    "Slayer Circlet",
    "Slayer Crown",
    "Spoils of War III",
    "Sponging",
    "Strategist Circlet",
    "Strategist Crown",
    "Street Demon Circlet",
    "Street Demon Crown",
    "Subscription Service",
    "Sword Overflow",
    "Syndicate Circlet",
    "Syndicate Crown",
    "Tactician's Kitchen",
    "Techie Circlet",
    "Techie Crown",
    "The Golden Egg",
    "Tiniest Titan",
    "Tiniest TItan+",
    "Tomb Raider II",
    "Trifecta II",
    "Unstable Evolution",
    "Upward Mobility",
    "Vanguard Circlet",
    "Vanguard Crown",
    "Void Swarm",
    "Wandering Trainer II",
    "Wand Overflow",
    "Wise Spending Woodland Charm",
    "Worth the Wait II",
]

# Lista unificada
todos_los_aumentos = list(set(aumentos_tier_1 + aumentos_tier_2 + aumentos_tier_3))
