tier_1 = [
    "AFK", "Augmented Power", "Band of Thieves I", "Beggars Can Be Choossers", "Best Friends I",
    "Big Friend I", "Branching Out", "Branching Out+", "Called Shot", "Caretaker's Ally",
    "Chaotic Evolution", "Climb The Ladder I", "Component Buffet", "Corrosion", "Crafted Crafting",
    "Crossfire", "Delayed Start", "Diversified Portfolio", "Diversified Portfolio+", "Dummify",
    "Efficient Shopper", "Eye For An Eye", "Eye For An Eye+", "Find Your Center", "Firesale",
    "Glass Cannon I", "Good For Something I", "Healing Orbs I", "Iron Assets", "Item Collector I",
    "Item Grab Bag I", "Keepers I", "Kingslayer", "Lategame Specialist", "Latent Forge", "Lineup",
    "Lit Fuse", "Lunch Money", "Missed Connections", "Nine Thousand Volts", "One, Two, Five!",
    "Ones Two Three", "Over Encumbered", "Pandora's Bench", "Pandora's Items", "Patience is a Virtue",
    "Perfect Form", "Placebo", "Placebo+", "Pocket Recombobulator", "Preparation I", "Pumping Up I",
    "Recombobulator", "Reroll Transfer", "Restart Mission", "Rigged Shop+", "Risky Moves",
    "Rolling For Days I", "Scoreboard Scrapper", "Shadow Homunculus", "Silver Destiny",
    "Silver Destiny+", "Silver Destiny++", "Silver Spoon", "Slice of Life", "Spoils of War I",
    "Stand United I", "Survivor", "Table Scraps", "Team Building", "Teaming Up I", "Teactonic Titan",
    "Titanic Titan", "Underdogs", "Young and Wild and Free"
]

tier_2 = [
    "A Magic Roll", "A Strory of Seven", "Adaptive Style", "Aim For The Top!", "All That Shimmers",
    "All That Shimmers+", "Another One!", "Another!+", "Ascension", "Backup Dancers", "Bastion Crest",
    "Battle Academia Crest", "Best Friends II", "Big Friend II", "Big Grab Bag", "Blazing Soul I",
    "Blood Rage", "Bronze For Life I", "Burning Birght", "Calculated Loss", "Care Package",
    "Caretaker's Favor", "Class President", "Clear Mind", "Climb The Ladder II", "Cloning Facility",
    "Cluttered Mind", "Cooking Pot", "Crossfire II", "Crown's Will", "Cry Me A River",
    "Crystal Gambit Crest", "Cybernetic Bulk II", "Cybernetic Implants II", "Cybernetic Uplink II",
    "Dazzling Display", "Deadlier Blades", "Deadlier Caps", "Deepening Shadows", "Destroyer Crest",
    "Diamond Hands", "Double Trouble", "Drop Blossom", "Duelist Crest", "Duo Queue", "Edgelord Crest",
    "Epoch", "Epoch+", "Escape Velocity", "Ethereal Blades", "Evil Beyond Measure",
    "Exclusive Customization", "Explosive Growth", "Explosive Growth+´", "Forward Thinking",
    "Fully Adapted", "Gain The Edge", "Game Plan", "Give 'em the Chair!", "Glass Cannon II",
    "Gold Destiny", "Gold Destiny+", "Gold For Dummies", "Golden Guillotine", "Golemify", "Grand Slam",
    "Hard Bargain", "Healing Orbs II", "Heavy is The Crown", "Heavyweight Crest", "Hefty Rolls",
    "Hero 101", "Heroic Grab Bag", "Heroic Grab Bag+", "Heroic Grab Bag++", "High Voltage",
    "Howling Gale", "Hustler", "I'll Be The Arms", "I'll Be The Legs", "Investment Strategy I",
    "Item Collector II", "Juggernaut Crest", "Keepers II", "Know Your Enemy", "Knuckledusters",
    "Last Second Save", "Last Stand", "Learn From The Beast", "Little Buddies", "Long Distance Pals",
    "Luchador Crest", "Mace's Will", "Malicious Monetization", "Moonlight", "NO SCOUT NO PIVOT",
    "New Contenders", "Noble Sacrifice", "Overheal", "Pair of Fours", "Pandora's Items II",
    "Patient Study", "Pilfer", "Plot Armor", "Portable Forge", "Power Upload", "Power of Friendship",
    "Precise Shot", "Preemptive Protection", "Preparation II", "Prizefighter", "Prodigy Crest",
    "Protector Crest", "Psychic Forge", "Pumping Up II", "Pyromaniac", "Quiet Quitting", "Raid Boss",
    "Raining Gold", "Raining Gold+", "ReinFOURcement", "Replication", "Ring The Bell",
    "Salvage Bing", "Salvage Bin+", "Sated Spellweaver", "Scapegoat", "Scavenger",
    "Schoolyard Justice", "Second Wind I", "Shimmerscale Essence", "Slammin'", "Slammin'+",
    "Solo Leveling", "Sorcerer Crest", "Soul Fighter Crest", "Space Camp", "Spear's Will",
    "Spirit Link", "Spoils of War II", "Star Guardian Crest", "Stars are Born", "Sunfire Board",
    "Supreme Cells Crest", "Teacher's Council", "Tesla Coil", "The God's Eye Opens",
    "The Strongest Survive", "Thorn-Plated Armor", "Time Skip", "Tiny Team", "Tomb Raider I",
    "Tons of Stats!", "Tournament Favorites", "Tournament TItans", "Tower Defense", "Trade Sector",
    "Transfer Students", "Treasure Hunt", "Trifecta I", "Two Much Value", "Two Trick", "Unceasing",
    "Vampiric Vitality", "Wandering Trainer I", "Warpath", "Water Lotus I", "Worth the Wait",
    "Wraith Crest"
]

tier_3 = [
    "A Hero Arrives!", "An Exalted Adventure", "And I'll Be The Head", "At What Cost",
    "Bastion Circlet", "Bastion Crown", "Battle Academia Circlet", "Battle Academia Crown",
    "Belt Overflow", "Birthday Present", "Blazing Soul II", "Bronze For Life II", "Build a Bud!",
    "Buried Treasures III", "Call to Chaos", "Caretaker's Chosen", "Coronation",
    "Crystal Gambit Circlet", "Crystal Gambit Crown", "Cybernetic Bulk III",
    "Cybernetic Implants III", "Cybernetic Uplink III", "Duelist Circlet", "Duelist Crown",
    "Edgelord Circlet", "Edgelord Crown", "Executioner Circlet", "Executioner Crown",
    "Expected Unexpectedness", "Final Ascension", "Flexible", "Going Long", "Grea Moonlight",
    "Hall of Mirrors", "Hard Commit", "Heavyweight Circlet", "Heavyweight Crown", "Hedge Fund",
    "Hold The Line", "Invested+", "Invested++", "Investment Strategy II", "Isekai",
    "Juggernaut Circlet", "Juggernaut Crown", "Level Up!", "Livin Forge", "Luchador Circlet",
    "Luchador Crown", "Lucky Gloves", "Lucky Gloves+", "Max Cap", "Mess Hall", "Nine Lives",
    "One Buff, Two Buff", "Pandora's Items III", "Prismatic Destiny", "Prismatic Pipeline",
    "Prismatic Ticket", "Prodigy Circlet", "Prodigy Crown", "Protagonist", "Protector Circlet",
    "Protector Crown", "Pumping Up III", "Quality Over Quantity", "Radiant Refactor",
    "Radiant Relics", "Roll The Dice", "Shopping Spree", "Sniper Circlet", "Sniper Crown",
    "Sorcerer Circlet", "Sorcerere Crown", "Soul Fighter Circlet", "Soul Fighter Crown",
    "Spoils of War III", "Sponging", "Star Guardian Circlet", "Star Guardian Crown", "Starter Kit",
    "Supreme Cells Circlet", "Supreme Cells Crown", "Sword Overflow", "Tactician's Kitchen",
    "The Golden Egg", "Tiniest Titan", "Tiniest Titan+", "Tomb Raider II", "Trickster's Treat",
    "Trifecta II", "Unlimited Power", "Upward Mobility", "Wand Overflow", "Wandering Trainer II",
    "Water Lotus II", "Worth the Wait II", "Wraith Circlet", "Wraith Crown"
]


# Lista unificada
todos_los_aumentos = list(set(tier_1 + tier_2 + tier_3))
